import { chromium } from 'playwright';
import fs from 'node:fs';
fs.writeFileSync('/tmp/d.txt','One sentence for testing. Another sentence follows here for the selection.');
const b = await chromium.launch({ args:['--no-sandbox'] });
const p = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto('http://127.0.0.1:5173/', { waitUntil:'networkidle' });
await p.setInputFiles('#fileInput','/tmp/d.txt');
await p.waitForSelector('#readStage.is-active');
const read = () => p.evaluate(() => { const x=document.querySelector('#practiceSelectionButton'); const s=getComputedStyle(x);
  return `disabled=${x.disabled} aria=${x.getAttribute('aria-disabled')} color=${s.color} bg=${s.backgroundColor} border=${s.borderColor} opacity=${s.opacity}`; });
console.log('NO SELECTION :', await read());
await p.evaluate(() => { const h=document.querySelector('#documentPreview').firstElementChild||document.querySelector('#documentPreview');
  const r=document.createRange(); r.selectNodeContents(h); const s=getSelection(); s.removeAllRanges(); s.addRange(r); });
await p.waitForTimeout(250);
console.log('WITH SELECTION :', await read());
await p.evaluate(() => getSelection().removeAllRanges());
await p.waitForTimeout(250);
console.log('CLEARED        :', await read());
await b.close();
